dataset_path: test_dataset.jsonl
lora_config:
  lora_alpha: 32
  r: 16
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
output_dir: test_output
quantization_config:
  bnb_4bit_quant_type: nf4
  load_in_4bit: true
training_args:
  num_train_epochs: 1
  per_device_train_batch_size: 1
